import type { Metadata } from "next";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { Analytics } from "@mui/icons-material";
// import { SpeedInsights } from "@vercel/speed-insights/next";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="h-full bg-white" suppressHydrationWarning>
			<body className="h-full">
				<AppRouterCacheProvider>{children}</AppRouterCacheProvider>
				<Analytics />
			</body>
		</html>
	);
}
